import type { HCP, HCPConnection } from "@/types/hcp"

export const mockHCPs: HCP[] = [
  {
    id: "hcp-1",
    name: "Dr. Emily Carter",
    specialty: "Cardiology",
    yearsExperience: 15,
    description: "Experienced and compassionate doctor specializing in cardiology",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face",
    peersCount: 232,
    followingCount: 124,
    patientsServed: 1000,
    patientsGrowth: 120,
    successRate: 95,
    successRateGrowth: 3,
    about:
      "Experienced cardiologist with a focus on preventive care and advanced cardiac interventions. Specializes in heart failure management and cardiac catheterization procedures.",
    education: [
      {
        institution: "Harvard Medical University",
        degree: "MD, Cardiology",
        specialization: "Interventional Cardiology",
        period: "Sep 2015 - Jun 2020",
      },
      {
        institution: "Johns Hopkins University",
        degree: "Residency in Internal Medicine",
        specialization: "Internal Medicine",
        period: "Jul 2008 - Jun 2012",
      },
    ],
    workExperience: [
      {
        institution: "Metropolitan Medical Center",
        position: "Senior Cardiologist",
        period: "2020 - Present",
        description: "Leading cardiac care team and performing complex interventional procedures",
      },
      {
        institution: "City General Hospital",
        position: "Cardiology Fellow",
        period: "2015 - 2020",
        description: "Specialized training in interventional cardiology and heart failure management",
      },
    ],
    publications: [
      {
        title: "Advanced Techniques in Cardiac Catheterization",
        journal: "Journal of Interventional Cardiology",
        year: 2023,
        coAuthors: ["Dr. Michael Rodriguez", "Dr. Sarah Johnson"],
      },
      {
        title: "Heart Failure Management in Elderly Patients",
        journal: "American Heart Journal",
        year: 2022,
        coAuthors: ["Dr. Robert Kim"],
      },
    ],
  },
  {
    id: "hcp-2",
    name: "Dr. Michael Rodriguez",
    specialty: "Neurology",
    yearsExperience: 12,
    description: "Neurologist specializing in brain disorders and cognitive health",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face",
    peersCount: 189,
    followingCount: 98,
    patientsServed: 850,
    patientsGrowth: 95,
    successRate: 92,
    successRateGrowth: 2,
    about:
      "Dedicated neurologist with expertise in treating complex neurological conditions and advancing brain health research. Specializes in stroke care and neurodegenerative diseases.",
    education: [
      {
        institution: "Johns Hopkins University",
        degree: "MD, Neurology",
        specialization: "Cognitive Neuroscience",
        period: "Sep 2012 - Jun 2017",
      },
    ],
    workExperience: [
      {
        institution: "Brain Health Institute",
        position: "Lead Neurologist",
        period: "2017 - Present",
        description: "Specializing in stroke care and neurodegenerative disease treatment",
      },
    ],
    publications: [
      {
        title: "Neuroplasticity in Stroke Recovery",
        journal: "Nature Neuroscience",
        year: 2023,
        coAuthors: ["Dr. Emily Carter"],
      },
    ],
  },
  {
    id: "hcp-3",
    name: "Dr. Sarah Johnson",
    specialty: "Oncology",
    yearsExperience: 18,
    description: "Leading oncologist with focus on cancer research and treatment",
    avatar: "https://images.unsplash.com/photo-1594824475317-29bb4b8b2b8e?w=150&h=150&fit=crop&crop=face",
    peersCount: 156,
    followingCount: 203,
    patientsServed: 1200,
    patientsGrowth: 140,
    successRate: 88,
    successRateGrowth: 4,
    about:
      "Pioneering oncologist dedicated to advancing cancer treatment through innovative research and compassionate patient care. Expert in immunotherapy and precision medicine.",
    education: [
      {
        institution: "Stanford Medical School",
        degree: "MD, Oncology",
        specialization: "Cancer Research",
        period: "Sep 2008 - Jun 2013",
      },
    ],
    workExperience: [
      {
        institution: "Cancer Research Center",
        position: "Senior Oncologist",
        period: "2013 - Present",
        description: "Leading clinical trials and developing new cancer treatment protocols",
      },
    ],
    publications: [
      {
        title: "Immunotherapy Advances in Lung Cancer",
        journal: "Journal of Clinical Oncology",
        year: 2023,
        coAuthors: ["Dr. Lisa Thompson"],
      },
    ],
  },
  {
    id: "hcp-4",
    name: "Dr. David Chen",
    specialty: "Pediatrics",
    yearsExperience: 8,
    description: "Pediatrician focused on child health and development",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&h=150&fit=crop&crop=face",
    peersCount: 134,
    followingCount: 87,
    patientsServed: 600,
    patientsGrowth: 80,
    successRate: 97,
    successRateGrowth: 1,
    about:
      "Compassionate pediatrician dedicated to ensuring the health and well-being of children through comprehensive care and family-centered approach.",
    education: [
      {
        institution: "UCLA Medical Center",
        degree: "MD, Pediatrics",
        specialization: "Child Development",
        period: "Sep 2014 - Jun 2019",
      },
    ],
    workExperience: [
      {
        institution: "Children's Hospital",
        position: "Pediatrician",
        period: "2019 - Present",
        description: "Providing comprehensive pediatric care and developmental assessments",
      },
    ],
    publications: [
      {
        title: "Early Childhood Development Milestones",
        journal: "Pediatrics Today",
        year: 2022,
        coAuthors: ["Dr. Michael Rodriguez"],
      },
    ],
  },
  {
    id: "hcp-5",
    name: "Dr. Lisa Thompson",
    specialty: "Dermatology",
    yearsExperience: 6,
    description: "Dermatologist specializing in skin health and cosmetic procedures",
    avatar: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=150&h=150&fit=crop&crop=face",
    peersCount: 98,
    followingCount: 156,
    patientsServed: 450,
    patientsGrowth: 65,
    successRate: 94,
    successRateGrowth: 2,
    about: "Expert dermatologist combining medical expertise with aesthetic treatments for comprehensive skin care.",
    education: [
      {
        institution: "Mayo Clinic",
        degree: "MD, Dermatology",
        specialization: "Cosmetic Dermatology",
        period: "Sep 2016 - Jun 2021",
      },
    ],
    workExperience: [
      {
        institution: "Skin Health Center",
        position: "Dermatologist",
        period: "2021 - Present",
        description: "Providing medical and cosmetic dermatology services",
      },
    ],
    publications: [
      {
        title: "Advances in Skin Cancer Detection",
        journal: "Dermatology Research",
        year: 2023,
        coAuthors: ["Dr. Sarah Johnson"],
      },
    ],
  },
  {
    id: "hcp-6",
    name: "Dr. Robert Kim",
    specialty: "Orthopedics",
    yearsExperience: 14,
    description: "Orthopedic surgeon specializing in joint replacement and sports medicine",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop&crop=face",
    peersCount: 167,
    followingCount: 112,
    patientsServed: 900,
    patientsGrowth: 110,
    successRate: 96,
    successRateGrowth: 3,
    about: "Skilled orthopedic surgeon with expertise in complex joint procedures and sports injury rehabilitation.",
    education: [
      {
        institution: "Cleveland Clinic",
        degree: "MD, Orthopedic Surgery",
        specialization: "Sports Medicine",
        period: "Sep 2010 - Jun 2015",
      },
    ],
    workExperience: [
      {
        institution: "Sports Medicine Institute",
        position: "Orthopedic Surgeon",
        period: "2015 - Present",
        description: "Specializing in joint replacement and sports injury treatment",
      },
    ],
    publications: [
      {
        title: "Minimally Invasive Joint Replacement Techniques",
        journal: "Orthopedic Surgery Today",
        year: 2022,
        coAuthors: ["Dr. Emily Carter"],
      },
    ],
  },
  {
    id: "hcp-7",
    name: "Dr. Maria Garcia",
    specialty: "Psychiatry",
    yearsExperience: 11,
    description: "Psychiatrist specializing in mental health and behavioral therapy",
    avatar: "https://images.unsplash.com/photo-1594824475317-29bb4b8b2b8e?w=150&h=150&fit=crop&crop=face",
    peersCount: 145,
    followingCount: 89,
    patientsServed: 680,
    patientsGrowth: 75,
    successRate: 91,
    successRateGrowth: 2,
    about: "Compassionate psychiatrist focused on holistic mental health treatment and patient well-being.",
    education: [
      {
        institution: "Yale Medical School",
        degree: "MD, Psychiatry",
        specialization: "Behavioral Therapy",
        period: "Sep 2013 - Jun 2018",
      },
    ],
    workExperience: [
      {
        institution: "Mental Health Center",
        position: "Psychiatrist",
        period: "2018 - Present",
        description: "Providing comprehensive mental health care and therapy services",
      },
    ],
    publications: [
      {
        title: "Cognitive Behavioral Therapy in Depression Treatment",
        journal: "Journal of Psychiatry",
        year: 2023,
      },
    ],
  },
  {
    id: "hcp-8",
    name: "Dr. James Wilson",
    specialty: "Emergency Medicine",
    yearsExperience: 9,
    description: "Emergency physician with expertise in critical care and trauma",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face",
    peersCount: 178,
    followingCount: 134,
    patientsServed: 920,
    patientsGrowth: 105,
    successRate: 93,
    successRateGrowth: 3,
    about: "Dedicated emergency physician with extensive experience in high-pressure medical situations.",
    education: [
      {
        institution: "University of Michigan",
        degree: "MD, Emergency Medicine",
        specialization: "Trauma Care",
        period: "Sep 2015 - Jun 2020",
      },
    ],
    workExperience: [
      {
        institution: "City Emergency Department",
        position: "Emergency Physician",
        period: "2020 - Present",
        description: "Providing critical care and emergency medical services",
      },
    ],
    publications: [
      {
        title: "Trauma Care Protocols in Emergency Medicine",
        journal: "Emergency Medicine Journal",
        year: 2022,
        coAuthors: ["Dr. Michael Rodriguez"],
      },
    ],
  },
  {
    id: "hcp-9",
    name: "Dr. Amanda Foster",
    specialty: "Radiology",
    yearsExperience: 7,
    description: "Radiologist specializing in diagnostic imaging and interventional procedures",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face",
    peersCount: 156,
    followingCount: 98,
    patientsServed: 520,
    patientsGrowth: 85,
    successRate: 96,
    successRateGrowth: 2,
    about: "Expert radiologist with advanced training in MRI, CT, and interventional radiology procedures.",
    education: [
      {
        institution: "University of Pennsylvania",
        degree: "MD, Radiology",
        specialization: "Interventional Radiology",
        period: "Sep 2017 - Jun 2022",
      },
    ],
    workExperience: [
      {
        institution: "Regional Medical Center",
        position: "Radiologist",
        period: "2022 - Present",
        description: "Performing diagnostic imaging and minimally invasive procedures",
      },
    ],
    publications: [
      {
        title: "AI in Medical Imaging: Current Applications",
        journal: "Radiology Today",
        year: 2023,
      },
    ],
  },
  {
    id: "hcp-10",
    name: "Dr. Kevin Park",
    specialty: "Anesthesiology",
    yearsExperience: 16,
    description: "Anesthesiologist with expertise in perioperative care and pain management",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&h=150&fit=crop&crop=face",
    peersCount: 134,
    followingCount: 76,
    patientsServed: 1150,
    patientsGrowth: 95,
    successRate: 98,
    successRateGrowth: 1,
    about: "Experienced anesthesiologist specializing in complex surgical procedures and chronic pain management.",
    education: [
      {
        institution: "Duke University",
        degree: "MD, Anesthesiology",
        specialization: "Pain Management",
        period: "Sep 2008 - Jun 2013",
      },
    ],
    workExperience: [
      {
        institution: "University Hospital",
        position: "Chief of Anesthesiology",
        period: "2013 - Present",
        description: "Leading anesthesia services and pain management programs",
      },
    ],
    publications: [
      {
        title: "Regional Anesthesia Techniques in Orthopedic Surgery",
        journal: "Anesthesia & Analgesia",
        year: 2022,
        coAuthors: ["Dr. Robert Kim"],
      },
    ],
  },
  {
    id: "hcp-11",
    name: "Dr. Rachel Martinez",
    specialty: "Obstetrics & Gynecology",
    yearsExperience: 5,
    description: "OB/GYN specialist focusing on women's health and maternal care",
    avatar: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=150&h=150&fit=crop&crop=face",
    peersCount: 98,
    followingCount: 145,
    patientsServed: 380,
    patientsGrowth: 110,
    successRate: 94,
    successRateGrowth: 3,
    about: "Dedicated OB/GYN physician providing comprehensive women's healthcare from adolescence through menopause.",
    education: [
      {
        institution: "Northwestern University",
        degree: "MD, Obstetrics & Gynecology",
        specialization: "Maternal-Fetal Medicine",
        period: "Sep 2019 - Jun 2024",
      },
    ],
    workExperience: [
      {
        institution: "Women's Health Center",
        position: "OB/GYN",
        period: "2024 - Present",
        description: "Providing obstetric and gynecological care with focus on high-risk pregnancies",
      },
    ],
    publications: [
      {
        title: "Advances in Prenatal Care and Screening",
        journal: "Obstetrics & Gynecology",
        year: 2023,
      },
    ],
  },
  {
    id: "hcp-12",
    name: "Dr. Thomas Anderson",
    specialty: "Gastroenterology",
    yearsExperience: 14,
    description: "Gastroenterologist specializing in digestive disorders and endoscopic procedures",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop&crop=face",
    peersCount: 167,
    followingCount: 89,
    patientsServed: 820,
    patientsGrowth: 75,
    successRate: 92,
    successRateGrowth: 2,
    about: "Expert gastroenterologist with extensive experience in inflammatory bowel disease and advanced endoscopy.",
    education: [
      {
        institution: "Washington University",
        degree: "MD, Gastroenterology",
        specialization: "Inflammatory Bowel Disease",
        period: "Sep 2010 - Jun 2015",
      },
    ],
    workExperience: [
      {
        institution: "Digestive Health Institute",
        position: "Gastroenterologist",
        period: "2015 - Present",
        description: "Treating complex digestive disorders and performing advanced endoscopic procedures",
      },
    ],
    publications: [
      {
        title: "Novel Therapies for Crohn's Disease",
        journal: "Gastroenterology",
        year: 2022,
      },
    ],
  },
]

export const mockConnections: HCPConnection[] = [
  {
    id: "conn-1",
    from: "hcp-1",
    to: "hcp-2",
    type: "Co-authored",
    description: "Co-authored 3 publications on cardiovascular-neurological connections",
    details: "Recent collaboration on heart-brain axis research with focus on stroke prevention in cardiac patients",
    strength: 4,
  },
  {
    id: "conn-2",
    from: "hcp-1",
    to: "hcp-3",
    type: "Referral",
    description: "Regular patient referrals for cardiac complications in cancer patients",
    details: "15+ successful referrals in the past year for cardio-oncology cases",
    strength: 3,
  },
  {
    id: "conn-3",
    from: "hcp-1",
    to: "hcp-6",
    type: "Colleague",
    description: "Work together at the same medical center",
    details: "Both practice at Metropolitan Medical Center, collaborate on patient care",
    strength: 2,
  },
  {
    id: "conn-4",
    from: "hcp-2",
    to: "hcp-4",
    type: "Research Collaboration",
    description: "Joint research on pediatric neurological development",
    details: "Currently working on a 2-year study funded by NIH on early brain development",
    strength: 5,
  },
  {
    id: "conn-5",
    from: "hcp-3",
    to: "hcp-5",
    type: "Co-authored",
    description: "Published research on skin cancer detection methods",
    details: "2 peer-reviewed publications on melanoma detection using AI technology",
    strength: 3,
  },
  {
    id: "conn-6",
    from: "hcp-4",
    to: "hcp-5",
    type: "Referral",
    description: "Pediatric dermatology referrals",
    details: "Specialized care for children with complex skin conditions and genetic disorders",
    strength: 2,
  },
  {
    id: "conn-7",
    from: "hcp-5",
    to: "hcp-6",
    type: "Mentor-Mentee",
    description: "Dr. Kim mentored Dr. Thompson during residency",
    details: "5-year mentorship relationship during dermatology residency program",
    strength: 4,
  },
  {
    id: "conn-8",
    from: "hcp-1",
    to: "hcp-7",
    type: "Referral",
    description: "Cardiac patients with anxiety disorders",
    details: "Mental health support for cardiac patients dealing with procedure anxiety and recovery stress",
    strength: 3,
  },
  {
    id: "conn-9",
    from: "hcp-7",
    to: "hcp-8",
    type: "Colleague",
    description: "Emergency psychiatric consultations",
    details: "On-call psychiatric support in ER for mental health crisis interventions",
    strength: 4,
  },
  {
    id: "conn-10",
    from: "hcp-2",
    to: "hcp-8",
    type: "Referral",
    description: "Neurological emergencies",
    details: "Stroke and head trauma cases requiring immediate neurological assessment",
    strength: 5,
  },
  {
    id: "conn-11",
    from: "hcp-9",
    to: "hcp-1",
    type: "Colleague",
    description: "Cardiac imaging collaboration",
    details: "Regular collaboration on cardiac CT and MRI interpretations",
    strength: 3,
  },
  {
    id: "conn-12",
    from: "hcp-10",
    to: "hcp-6",
    type: "Colleague",
    description: "Orthopedic surgery anesthesia",
    details: "Primary anesthesiologist for Dr. Kim's complex joint replacement surgeries",
    strength: 4,
  },
  {
    id: "conn-13",
    from: "hcp-11",
    to: "hcp-4",
    type: "Referral",
    description: "Pediatric gynecology consultations",
    details: "Adolescent health and developmental concerns referrals",
    strength: 2,
  },
  {
    id: "conn-14",
    from: "hcp-12",
    to: "hcp-3",
    type: "Referral",
    description: "GI complications in cancer patients",
    details: "Managing digestive side effects of cancer treatments",
    strength: 3,
  },
  {
    id: "conn-15",
    from: "hcp-9",
    to: "hcp-12",
    type: "Colleague",
    description: "GI imaging procedures",
    details: "Collaborative work on advanced imaging for digestive disorders",
    strength: 3,
  },
]
